//todo: remove mock functionality - replace with real API data
export const MOCK_SERVICES = [
  {
    id: "1",
    name: "Jasper AI",
    subtitle: "AI Copywriting",
    description: "Content creation for marketing, blogs, and social media",
    fullDescription: "Jasper AI is an advanced AI writing assistant that helps create high-quality content for blogs, marketing campaigns, social media posts, and more. With over 50+ templates and support for 25+ languages, Jasper streamlines your content creation process.",
    category: "copywriting",
    price: "Freemium",
    rating: "4.8",
    icon: "✨",
    color: "#6366f1",
    logoUrl: "https://www.jasper.ai/favicon.ico",
    features: [
      "50+ AI templates",
      "SEO mode for optimized content",
      "Multi-language support (25+ languages)",
      "Plagiarism checker",
      "Team collaboration tools",
      "Chrome extension"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["10,000 words/month", "Basic templates", "1 user"] },
      { name: "Starter", price: "$49/mo", features: ["100,000 words/month", "All templates", "SEO mode", "1 user"] },
      { name: "Boss Mode", price: "$99/mo", features: ["Unlimited words", "All features", "Priority support", "3 users"] }
    ],
    useCases: ["Blog writing", "Ad copy", "Product descriptions", "Social media content", "Email marketing"],
    website: "https://jasper.ai",
    popularity: 9500,
    createdAt: new Date('2025-08-15'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "Team Collaboration", "Multi-language", "SEO Tools"],
    commonUseCases: ["Content Marketing", "SEO", "Social Media", "Email Marketing"],
    jobTitles: ["Content Writer", "Marketing Manager", "Social Media Manager"],
  },
  {
    id: "2",
    name: "Canva AI",
    subtitle: "Design & Visuals",
    description: "Create stunning designs with AI-powered tools",
    fullDescription: "Canva AI revolutionizes graphic design with intelligent tools that help you create professional visuals in minutes. From social media graphics to presentations, Canva's AI assists with design suggestions, background removal, and smart resizing.",
    category: "design",
    price: "Freemium",
    rating: "4.9",
    icon: "🎨",
    color: "#ec4899",
    logoUrl: "https://www.canva.com/favicon.ico",
    features: [
      "AI-powered design suggestions",
      "Magic Eraser & Background Remover",
      "250,000+ templates",
      "Brand kit management",
      "Video editing tools",
      "Team collaboration"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["Basic templates", "5GB storage", "Limited AI features"] },
      { name: "Pro", price: "$12.99/mo", features: ["Premium templates", "100GB storage", "All AI features", "Brand kit"] },
      { name: "Teams", price: "$14.99/user/mo", features: ["Everything in Pro", "Unlimited storage", "Team features"] }
    ],
    useCases: ["Social media graphics", "Presentations", "Marketing materials", "Logos", "Video content"],
    website: "https://canva.com",
    popularity: 12000,
    createdAt: new Date('2024-11-20'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Team Collaboration", "Mobile App", "Integrations"],
    commonUseCases: ["Design", "Social Media", "Marketing"],
    jobTitles: ["Graphic Designer", "Social Media Manager", "Marketing Manager"],
  },
  {
    id: "3",
    name: "Copy.ai",
    subtitle: "Marketing Texts",
    description: "Generate high-converting marketing copy instantly",
    fullDescription: "Copy.ai uses advanced AI to generate persuasive marketing copy for ads, emails, websites, and more. Perfect for marketers who need to produce engaging content quickly without sacrificing quality.",
    category: "marketing",
    price: "Freemium",
    rating: "4.7",
    icon: "📝",
    color: "#8b5cf6",
    logoUrl: "https://www.copy.ai/favicon.ico",
    features: [
      "90+ copywriting tools",
      "Blog post wizard",
      "Sales copy generator",
      "Email sequences",
      "Product descriptions",
      "A/B testing suggestions"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["2,000 words/month", "Basic tools", "1 user"] },
      { name: "Pro", price: "$49/mo", features: ["Unlimited words", "All tools", "Priority support", "5 users"] },
      { name: "Enterprise", price: "Custom", features: ["Custom AI training", "Dedicated support", "Unlimited users"] }
    ],
    useCases: ["Ad copy", "Email marketing", "Landing pages", "Product launches", "Sales funnels"],
    website: "https://copy.ai",
    popularity: 8200,
    createdAt: new Date('2025-09-10'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["API Access", "Team Collaboration"],
    commonUseCases: ["Marketing", "Email Marketing", "Content Marketing"],
    jobTitles: ["Marketing Manager", "Content Writer"],
  },
  {
    id: "4",
    name: "Grammarly",
    subtitle: "Text Checking",
    description: "Advanced grammar and writing enhancement",
    fullDescription: "Grammarly is your AI-powered writing assistant that checks grammar, spelling, punctuation, and style. It provides real-time suggestions to improve clarity, engagement, and delivery across all your writing.",
    category: "text",
    price: "Freemium",
    rating: "4.6",
    icon: "✍️",
    color: "#10b981",
    logoUrl: "https://www.grammarly.com/favicon.ico",
    features: [
      "Grammar & spelling check",
      "Tone detector",
      "Plagiarism checker (Premium)",
      "Writing clarity suggestions",
      "Genre-specific style checks",
      "Integration with 500,000+ apps"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["Basic grammar check", "Tone detection", "Limited suggestions"] },
      { name: "Premium", price: "$12/mo", features: ["Advanced grammar", "Plagiarism checker", "Style suggestions"] },
      { name: "Business", price: "$15/user/mo", features: ["Team features", "Brand tone", "Analytics dashboard"] }
    ],
    useCases: ["Business emails", "Academic writing", "Content creation", "Professional documents"],
    website: "https://grammarly.com",
    popularity: 15000,
    createdAt: new Date('2024-08-05'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "Integrations", "Mobile App"],
    commonUseCases: ["Content Marketing", "Email Marketing"],
    jobTitles: ["Content Writer", "Customer Support Agent"],
  },
  {
    id: "5",
    name: "ChatGPT Plus",
    subtitle: "Universal AI",
    description: "Advanced AI assistant for any task",
    fullDescription: "ChatGPT Plus gives you access to GPT-4, the most advanced AI model for conversations, coding, creative writing, analysis, and problem-solving. With faster response times and priority access during peak hours.",
    category: "chat",
    logoUrl: "https://chat.openai.com/favicon.ico",
    price: "Freemium",
    rating: "4.9",
    icon: "🤖",
    color: "#14b8a6",
    features: [
      "GPT-4 access",
      "Faster response times",
      "Priority access during peak times",
      "Early access to new features",
      "Advanced data analysis",
      "Image generation (DALL-E 3)"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["GPT-3.5 access", "Standard response time", "Basic features"] },
      { name: "Plus", price: "$20/mo", features: ["GPT-4 access", "Priority access", "All features", "Image generation"] }
    ],
    useCases: ["Coding assistance", "Research", "Creative writing", "Problem solving", "Learning"],
    website: "https://chat.openai.com",
    popularity: 20000,
    createdAt: new Date('2025-07-01'),
    teamSize: ["individual"],
    hasFreeTier: true,
    popularFeatures: ["API Access", "Mobile App"],
    commonUseCases: ["Content Marketing", "Data Analysis"],
    jobTitles: ["Content Writer", "Marketing Manager", "Customer Support Agent"],
  },
  {
    id: "6",
    name: "Buffer AI",
    subtitle: "Social Media",
    description: "Optimize your social media strategy with AI",
    fullDescription: "Buffer AI helps you plan, create, and schedule social media content with AI-powered suggestions. Get optimal posting times, content ideas, and performance analytics all in one platform.",
    category: "social",
    price: "Freemium",
    rating: "4.5",
    icon: "📱",
    color: "#f59e0b",
    logoUrl: "https://buffer.com/favicon.ico",
    features: [
      "AI content suggestions",
      "Optimal posting times",
      "Multi-platform scheduling",
      "Analytics dashboard",
      "Team collaboration",
      "Hashtag recommendations"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["3 social channels", "10 scheduled posts", "Basic analytics"] },
      { name: "Essentials", price: "$6/mo", features: ["All channels", "Unlimited posts", "AI suggestions"] },
      { name: "Team", price: "$12/user/mo", features: ["Team features", "Advanced analytics", "Priority support"] }
    ],
    useCases: ["Social media management", "Content planning", "Team collaboration", "Analytics tracking"],
    website: "https://buffer.com",
    popularity: 7500,
    createdAt: new Date('2025-04-12'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["Team Collaboration", "Integrations"],
    commonUseCases: ["Social Media", "Marketing"],
    jobTitles: ["Social Media Manager", "Marketing Manager"],
  },
  {
    id: "7",
    name: "Writesonic",
    subtitle: "AI Content Writer",
    description: "AI writing tool for articles, blogs, and ads",
    fullDescription: "Writesonic is an AI-powered writing platform that creates SEO-optimized content for blogs, ads, emails, and websites. With advanced AI models, it helps you generate engaging content in seconds.",
    category: "copywriting",
    price: "Freemium",
    rating: "4.6",
    icon: "✨",
    color: "#8b5cf6",
    logoUrl: "https://writesonic.com/favicon.ico",
    features: [
      "AI article writer",
      "SEO optimization",
      "Multi-language support",
      "Plagiarism checker",
      "Chrome extension",
      "Brand voice"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["10,000 words/month", "Basic features", "GPT-3.5"] },
      { name: "Pro", price: "$19/mo", features: ["Unlimited words", "GPT-4", "All features"] },
      { name: "Enterprise", price: "Custom", features: ["Custom AI", "Dedicated support", "API access"] }
    ],
    useCases: ["Blog writing", "Ad copy", "SEO content", "Email marketing", "Product descriptions"],
    website: "https://writesonic.com",
    popularity: 7800,
    createdAt: new Date('2025-09-20'),
    teamSize: ["individual", "small"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "API Access", "Multi-language", "SEO Tools"],
    commonUseCases: ["Content Marketing", "SEO", "Email Marketing"],
    jobTitles: ["Content Writer", "Marketing Manager"],
  },
  {
    id: "8",
    name: "Adobe Firefly",
    subtitle: "Generative AI",
    description: "Create stunning images and effects with AI",
    fullDescription: "Adobe Firefly is a generative AI tool that creates images, text effects, and design elements from simple text descriptions. Integrated with Creative Cloud, Firefly helps designers explore ideas and iterate faster.",
    category: "design",
    price: "Freemium",
    rating: "4.8",
    icon: "🎨",
    color: "#f59e0b",
    logoUrl: "https://www.adobe.com/favicon.ico",
    features: [
      "Text to image generation",
      "Generative fill",
      "Text effects",
      "Creative Cloud integration",
      "Commercial safe assets",
      "Style presets"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["25 credits/month", "Basic features", "Watermarked"] },
      { name: "Premium", price: "$14.99/mo", features: ["100 credits/month", "All features", "No watermark", "Commercial use"] },
      { name: "Creative Cloud", price: "$54.99/mo", features: ["Unlimited credits", "Full CC suite", "Cloud storage"] }
    ],
    useCases: ["Concept art", "Social media graphics", "Marketing visuals", "Product mockups", "Illustrations"],
    website: "https://firefly.adobe.com",
    popularity: 9800,
    createdAt: new Date('2025-05-15'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Integrations", "Mobile App"],
    commonUseCases: ["Design", "Marketing", "Social Media"],
    jobTitles: ["Graphic Designer", "Marketing Manager"],
  },
];

export interface Job {
  id: string;
  title: string;
  aiImpact: number; // 0-100
  tasksCount: number;
  aisCount: number;
  category: string;
  description: string;
  tasks: string[]; // Professional tasks within this job
}

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Content Writer",
    aiImpact: 85,
    tasksCount: 12,
    aisCount: 8,
    category: "Creative",
    description: "Creates written content for websites, blogs, and marketing materials",
    tasks: [
      "Write blog posts and articles",
      "Create SEO-optimized content",
      "Develop marketing copy",
      "Edit and proofread content",
      "Research industry topics",
      "Write product descriptions",
      "Create social media captions",
      "Develop email newsletters",
      "Write case studies",
      "Create white papers",
      "Develop landing page copy",
      "Manage content calendar"
    ]
  },
  {
    id: "2",
    title: "Graphic Designer",
    aiImpact: 72,
    tasksCount: 15,
    aisCount: 10,
    category: "Creative",
    description: "Designs visual content for digital and print media",
    tasks: [
      "Create social media graphics",
      "Design marketing materials",
      "Develop brand identity",
      "Create infographics",
      "Design website layouts",
      "Edit and retouch images",
      "Create presentation templates",
      "Design print materials (brochures, flyers)",
      "Develop icon sets",
      "Create illustrations",
      "Design email templates",
      "Manage brand guidelines",
      "Create packaging designs",
      "Design advertisements",
      "Develop motion graphics"
    ]
  },
  {
    id: "3",
    title: "Software Developer",
    aiImpact: 68,
    tasksCount: 20,
    aisCount: 12,
    category: "Technology",
    description: "Develops and maintains software applications",
    tasks: []
  },
  {
    id: "4",
    title: "Data Analyst",
    aiImpact: 78,
    tasksCount: 14,
    aisCount: 9,
    category: "Analytics",
    description: "Analyzes data to provide business insights",
    tasks: []
  },
  {
    id: "5",
    title: "Marketing Manager",
    aiImpact: 65,
    tasksCount: 18,
    aisCount: 11,
    category: "Marketing",
    description: "Plans and executes marketing strategies",
    tasks: [
      "Develop marketing strategy",
      "Plan campaign budgets",
      "Analyze market trends",
      "Coordinate team activities",
      "Manage marketing campaigns",
      "Track campaign performance",
      "Create marketing reports",
      "Conduct market research",
      "Manage brand positioning",
      "Oversee content creation",
      "Develop product launches",
      "Manage vendor relationships",
      "Coordinate events and webinars",
      "Optimize marketing funnels",
      "Manage email marketing",
      "Analyze competitor strategies",
      "Set KPIs and goals",
      "Present results to stakeholders"
    ]
  },
  {
    id: "6",
    title: "Customer Support Agent",
    aiImpact: 82,
    tasksCount: 10,
    aisCount: 7,
    category: "Service",
    description: "Provides customer service and technical support",
    tasks: [
      "Respond to customer inquiries",
      "Resolve customer complaints",
      "Provide technical support",
      "Update customer records",
      "Create support documentation",
      "Process refunds and returns",
      "Escalate complex issues",
      "Track support metrics",
      "Train new support staff",
      "Improve customer satisfaction"
    ]
  },
  {
    id: "7",
    title: "Social Media Manager",
    aiImpact: 88,
    tasksCount: 16,
    aisCount: 13,
    category: "Marketing",
    description: "Manages social media presence and engagement",
    tasks: [
      "Create social media content",
      "Schedule and publish posts",
      "Respond to comments and messages",
      "Analyze engagement metrics",
      "Develop content calendar",
      "Run social media campaigns",
      "Create social media graphics",
      "Write engaging captions",
      "Monitor brand mentions",
      "Manage influencer partnerships",
      "Create video content",
      "Develop hashtag strategy",
      "Track competitor activity",
      "Report on social performance",
      "Manage community engagement",
      "Create social media ads"
    ]
  },
  {
    id: "8",
    title: "Copywriter",
    aiImpact: 87,
    tasksCount: 11,
    aisCount: 9,
    category: "Creative",
    description: "Writes persuasive copy for ads and marketing",
    tasks: []
  },
  {
    id: "9",
    title: "UX/UI Designer",
    aiImpact: 60,
    tasksCount: 17,
    aisCount: 8,
    category: "Creative",
    description: "Designs user experiences and interfaces",
    tasks: []
  },
  {
    id: "10",
    title: "Product Manager",
    aiImpact: 55,
    tasksCount: 22,
    aisCount: 10,
    category: "Management",
    description: "Manages product development and strategy",
    tasks: []
  },
  {
    id: "11",
    title: "Video Editor",
    aiImpact: 75,
    tasksCount: 13,
    aisCount: 11,
    category: "Creative",
    description: "Edits and produces video content",
    tasks: []
  },
  {
    id: "12",
    title: "Translator",
    aiImpact: 90,
    tasksCount: 8,
    aisCount: 6,
    category: "Language",
    description: "Translates content between languages",
    tasks: []
  },
  {
    id: "13",
    title: "Sales Representative",
    aiImpact: 58,
    tasksCount: 19,
    aisCount: 9,
    category: "Sales",
    description: "Sells products and services to customers",
    tasks: []
  },
  {
    id: "14",
    title: "Email Marketer",
    aiImpact: 83,
    tasksCount: 12,
    aisCount: 10,
    category: "Marketing",
    description: "Creates and manages email marketing campaigns",
    tasks: []
  },
  {
    id: "15",
    title: "SEO Specialist",
    aiImpact: 70,
    tasksCount: 15,
    aisCount: 12,
    category: "Marketing",
    description: "Optimizes content for search engines",
    tasks: []
  },
  {
    id: "16",
    title: "Business Analyst",
    aiImpact: 66,
    tasksCount: 18,
    aisCount: 11,
    category: "Analytics",
    description: "Analyzes business processes and requirements",
    tasks: []
  },
  {
    id: "17",
    title: "HR Recruiter",
    aiImpact: 62,
    tasksCount: 16,
    aisCount: 8,
    category: "Human Resources",
    description: "Recruits and screens job candidates",
    tasks: []
  },
  {
    id: "18",
    title: "Financial Analyst",
    aiImpact: 73,
    tasksCount: 17,
    aisCount: 10,
    category: "Finance",
    description: "Analyzes financial data and trends",
    tasks: []
  },
  {
    id: "19",
    title: "Project Manager",
    aiImpact: 52,
    tasksCount: 20,
    aisCount: 9,
    category: "Management",
    description: "Manages projects and coordinates teams",
    tasks: []
  },
  {
    id: "20",
    title: "Research Analyst",
    aiImpact: 76,
    tasksCount: 14,
    aisCount: 11,
    category: "Analytics",
    description: "Conducts research and data analysis",
    tasks: []
  }
];
