//todo: remove mock functionality - replace with real API data
export const MOCK_SERVICES = [
  {
    id: "1",
    name: "Jasper AI",
    subtitle: "AI Copywriting",
    description: "Content creation for marketing, blogs, and social media",
    fullDescription: "Jasper AI is an advanced AI writing assistant that helps create high-quality content for blogs, marketing campaigns, social media posts, and more. With over 50+ templates and support for 25+ languages, Jasper streamlines your content creation process.",
    category: "copywriting",
    price: "Freemium",
    rating: "4.8",
    icon: "✨",
    color: "#6366f1",
    logoUrl: "https://www.jasper.ai/favicon.ico",
    features: [
      "50+ AI templates",
      "SEO mode for optimized content",
      "Multi-language support (25+ languages)",
      "Plagiarism checker",
      "Team collaboration tools",
      "Chrome extension"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["10,000 words/month", "Basic templates", "1 user"] },
      { name: "Starter", price: "$49/mo", features: ["100,000 words/month", "All templates", "SEO mode", "1 user"] },
      { name: "Boss Mode", price: "$99/mo", features: ["Unlimited words", "All features", "Priority support", "3 users"] }
    ],
    useCases: ["Blog writing", "Ad copy", "Product descriptions", "Social media content", "Email marketing"],
    website: "https://jasper.ai",
    popularity: 9500,
    createdAt: new Date('2025-08-15'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "Team Collaboration", "Multi-language", "SEO Tools"],
    commonUseCases: ["Content Marketing", "SEO", "Social Media", "Email Marketing"],
  },
  {
    id: "2",
    name: "Canva AI",
    subtitle: "Design & Visuals",
    description: "Create stunning designs with AI-powered tools",
    fullDescription: "Canva AI revolutionizes graphic design with intelligent tools that help you create professional visuals in minutes. From social media graphics to presentations, Canva's AI assists with design suggestions, background removal, and smart resizing.",
    category: "design",
    price: "Freemium",
    rating: "4.9",
    icon: "🎨",
    color: "#ec4899",
    logoUrl: "https://www.canva.com/favicon.ico",
    features: [
      "AI-powered design suggestions",
      "Magic Eraser & Background Remover",
      "250,000+ templates",
      "Brand kit management",
      "Video editing tools",
      "Team collaboration"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["Basic templates", "5GB storage", "Limited AI features"] },
      { name: "Pro", price: "$12.99/mo", features: ["Premium templates", "100GB storage", "All AI features", "Brand kit"] },
      { name: "Teams", price: "$14.99/user/mo", features: ["Everything in Pro", "Unlimited storage", "Team features"] }
    ],
    useCases: ["Social media graphics", "Presentations", "Marketing materials", "Logos", "Video content"],
    website: "https://canva.com",
    popularity: 12000,
    createdAt: new Date('2024-11-20'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Team Collaboration", "Mobile App", "Integrations"],
    commonUseCases: ["Design", "Social Media", "Marketing"],
  },
  {
    id: "3",
    name: "Copy.ai",
    subtitle: "Marketing Texts",
    description: "Generate high-converting marketing copy instantly",
    fullDescription: "Copy.ai uses advanced AI to generate persuasive marketing copy for ads, emails, websites, and more. Perfect for marketers who need to produce engaging content quickly without sacrificing quality.",
    category: "marketing",
    price: "Freemium",
    rating: "4.7",
    icon: "📝",
    color: "#8b5cf6",
    logoUrl: "https://www.copy.ai/favicon.ico",
    features: [
      "90+ copywriting tools",
      "Blog post wizard",
      "Sales copy generator",
      "Email sequences",
      "Product descriptions",
      "A/B testing suggestions"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["2,000 words/month", "Basic tools", "1 user"] },
      { name: "Pro", price: "$49/mo", features: ["Unlimited words", "All tools", "Priority support", "5 users"] },
      { name: "Enterprise", price: "Custom", features: ["Custom AI training", "Dedicated support", "Unlimited users"] }
    ],
    useCases: ["Ad copy", "Email marketing", "Landing pages", "Product launches", "Sales funnels"],
    website: "https://copy.ai",
    popularity: 8200,
    createdAt: new Date('2025-09-10'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["API Access", "Team Collaboration"],
    commonUseCases: ["Marketing", "Email Marketing", "Content Marketing"],
  },
  {
    id: "4",
    name: "Grammarly",
    subtitle: "Text Checking",
    description: "Advanced grammar and writing enhancement",
    fullDescription: "Grammarly is your AI-powered writing assistant that checks grammar, spelling, punctuation, and style. It provides real-time suggestions to improve clarity, engagement, and delivery across all your writing.",
    category: "text",
    price: "Freemium",
    rating: "4.6",
    icon: "✍️",
    color: "#10b981",
    logoUrl: "https://www.grammarly.com/favicon.ico",
    features: [
      "Grammar & spelling check",
      "Tone detector",
      "Plagiarism checker (Premium)",
      "Writing clarity suggestions",
      "Genre-specific style checks",
      "Integration with 500,000+ apps"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["Basic grammar check", "Tone detection", "Limited suggestions"] },
      { name: "Premium", price: "$12/mo", features: ["Advanced grammar", "Plagiarism checker", "Style suggestions"] },
      { name: "Business", price: "$15/user/mo", features: ["Team features", "Brand tone", "Analytics dashboard"] }
    ],
    useCases: ["Business emails", "Academic writing", "Content creation", "Professional documents"],
    website: "https://grammarly.com",
    popularity: 15000,
    createdAt: new Date('2024-08-05'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "Integrations", "Mobile App"],
    commonUseCases: ["Content Marketing", "Email Marketing"],
  },
  {
    id: "5",
    name: "ChatGPT Plus",
    subtitle: "Universal AI",
    description: "Advanced AI assistant for any task",
    fullDescription: "ChatGPT Plus gives you access to GPT-4, the most advanced AI model for conversations, coding, creative writing, analysis, and problem-solving. With faster response times and priority access during peak hours.",
    category: "chat",
    logoUrl: "https://chat.openai.com/favicon.ico",
    price: "Freemium",
    rating: "4.9",
    icon: "🤖",
    color: "#14b8a6",
    features: [
      "GPT-4 access",
      "Faster response times",
      "Priority access during peak times",
      "Early access to new features",
      "Advanced data analysis",
      "Image generation (DALL-E 3)"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["GPT-3.5 access", "Standard response time", "Basic features"] },
      { name: "Plus", price: "$20/mo", features: ["GPT-4 access", "Priority access", "All features", "Image generation"] }
    ],
    useCases: ["Coding assistance", "Research", "Creative writing", "Problem solving", "Learning"],
    website: "https://chat.openai.com",
    popularity: 20000,
    createdAt: new Date('2025-07-01'),
    teamSize: ["individual"],
    hasFreeTier: true,
    popularFeatures: ["API Access", "Mobile App"],
    commonUseCases: ["Content Marketing", "Data Analysis"],
  },
  {
    id: "6",
    name: "Buffer AI",
    subtitle: "Social Media",
    description: "Optimize your social media strategy with AI",
    fullDescription: "Buffer AI helps you plan, create, and schedule social media content with AI-powered suggestions. Get optimal posting times, content ideas, and performance analytics all in one platform.",
    category: "social",
    price: "Freemium",
    rating: "4.5",
    icon: "📱",
    color: "#f59e0b",
    logoUrl: "https://buffer.com/favicon.ico",
    features: [
      "AI content suggestions",
      "Optimal posting times",
      "Multi-platform scheduling",
      "Analytics dashboard",
      "Team collaboration",
      "Hashtag recommendations"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["3 social channels", "10 scheduled posts", "Basic analytics"] },
      { name: "Essentials", price: "$6/mo", features: ["All channels", "Unlimited posts", "AI suggestions"] },
      { name: "Team", price: "$12/user/mo", features: ["Team features", "Advanced analytics", "Priority support"] }
    ],
    useCases: ["Social media management", "Content planning", "Team collaboration", "Analytics tracking"],
    website: "https://buffer.com",
    popularity: 7500,
    createdAt: new Date('2025-04-12'),
    teamSize: ["individual", "small", "medium"],
    hasFreeTier: true,
    popularFeatures: ["Team Collaboration", "Integrations"],
    commonUseCases: ["Social Media", "Marketing"],
  },
  {
    id: "7",
    name: "Writesonic",
    subtitle: "AI Content Writer",
    description: "AI writing tool for articles, blogs, and ads",
    fullDescription: "Writesonic is an AI-powered writing platform that creates SEO-optimized content for blogs, ads, emails, and websites. With advanced AI models, it helps you generate engaging content in seconds.",
    category: "copywriting",
    price: "Freemium",
    rating: "4.6",
    icon: "✨",
    color: "#8b5cf6",
    logoUrl: "https://writesonic.com/favicon.ico",
    features: [
      "AI article writer",
      "SEO optimization",
      "Multi-language support",
      "Plagiarism checker",
      "Chrome extension",
      "Brand voice"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["10,000 words/month", "Basic features", "GPT-3.5"] },
      { name: "Pro", price: "$19/mo", features: ["Unlimited words", "GPT-4", "All features"] },
      { name: "Enterprise", price: "Custom", features: ["Custom AI", "Dedicated support", "API access"] }
    ],
    useCases: ["Blog writing", "Ad copy", "SEO content", "Email marketing", "Product descriptions"],
    website: "https://writesonic.com",
    popularity: 7800,
    createdAt: new Date('2025-09-20'),
    teamSize: ["individual", "small"],
    hasFreeTier: true,
    popularFeatures: ["Browser Extension", "API Access", "Multi-language", "SEO Tools"],
    commonUseCases: ["Content Marketing", "SEO", "Email Marketing"],
  },
  {
    id: "8",
    name: "Adobe Firefly",
    subtitle: "Generative AI",
    description: "Create stunning images and effects with AI",
    fullDescription: "Adobe Firefly is a generative AI tool that creates images, text effects, and design elements from simple text descriptions. Integrated with Creative Cloud, Firefly helps designers explore ideas and iterate faster.",
    category: "design",
    price: "Freemium",
    rating: "4.8",
    icon: "🎨",
    color: "#f59e0b",
    logoUrl: "https://www.adobe.com/favicon.ico",
    features: [
      "Text to image generation",
      "Generative fill",
      "Text effects",
      "Creative Cloud integration",
      "Commercial safe assets",
      "Style presets"
    ],
    pricingTiers: [
      { name: "Free", price: "$0", features: ["25 credits/month", "Basic features", "Watermarked"] },
      { name: "Premium", price: "$14.99/mo", features: ["100 credits/month", "All features", "No watermark", "Commercial use"] },
      { name: "Creative Cloud", price: "$54.99/mo", features: ["Unlimited credits", "Full CC suite", "Cloud storage"] }
    ],
    useCases: ["Concept art", "Social media graphics", "Marketing visuals", "Product mockups", "Illustrations"],
    website: "https://firefly.adobe.com",
    popularity: 9800,
    createdAt: new Date('2025-05-15'),
    teamSize: ["individual", "small", "medium", "enterprise"],
    hasFreeTier: true,
    popularFeatures: ["Integrations", "Mobile App"],
    commonUseCases: ["Design", "Marketing", "Social Media"],
  },
];
